orion_data_path: "../data/orion_customer_data.csv"

columns_to_use:
  - customer_id
  - customer_age
  - gender
  - total_purchase_last_3_months
  - purchase_month_1
  - purchase_month_2
  - purchase_month_3
  - purchase_week_1
  - purchase_week_2
  - purchase_week_3
  - purchase_week_4
  - category_Books
  - category_Clothing
  - category_Electronics
  - category_Home
  - most_common_payment_method

columns_to_encode:
  - gender
  - most_common_payment_method

numerical_features:
  - customer_age
  - total_purchase_last_3_months
  - purchase_month_1
  - purchase_month_2
  - purchase_month_3
  - purchase_week_1
  - purchase_week_2
  - purchase_week_3
  - purchase_week_4

one_hot_encoded_features:
  - category_Books
  - category_Clothing
  - category_Electronics
  - category_Home
  - gender_Female
  - gender_Male
  - most_common_payment_method_Cash
  - most_common_payment_method_Credit Card
  - most_common_payment_method_Crypto
  - most_common_payment_method_PayPal

