numerical_features:
  - customer_age
  - total_purchase_last_3_months
  - purchase_month_1
  - purchase_month_2
  - purchase_month_3
  - purchase_week_1
  - purchase_week_2
  - purchase_week_3
  - purchase_week_4

one_hot_encoded_features:
  - category_books
  - category_clothing
  - category_electronics
  - category_home
  - gender_female
  - gender_male
  - most_common_payment_method_cash
  - most_common_payment_method_credit_card
  - most_common_payment_method_crypto
  - most_common_payment_method_paypal

eps: 2.2
min_samples: 10

avg_columns:
  - customer_age
  - total_purchase_last_3_months
  - purchase_month_1
  - purchase_month_2
  - purchase_month_3
  - purchase_week_1
  - purchase_week_2
  - purchase_week_3
  - purchase_week_4

sum_columns:
  - category_books
  - category_clothing
  - category_electronics
  - category_home
  - gender_female
  - gender_male
  - most_common_payment_method_cash
  - most_common_payment_method_credit_card
  - most_common_payment_method_crypto
  - most_common_payment_method_paypal

range_columns:
  - customer_age